# Generated by Django 4.2.6 on 2023-11-22 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("landingpage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donate",
            name="data",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
