# Generated by Django 4.2.6 on 2023-10-31 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("local", models.CharField(max_length=20)),
                (
                    "data_evento",
                    models.DateTimeField(verbose_name="Dia e horário do evento"),
                ),
                ("data_post", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
