# Generated by Django 4.2.6 on 2023-11-01 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_evento_anunciado_por"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evento",
            old_name="decription",
            new_name="description",
        ),
    ]
