# Generated by Django 4.2.6 on 2023-11-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_rename_decription_evento_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_palestrante",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="palestrante",
            name="is_visitant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="palestrante",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="foto"
            ),
        ),
    ]
