# Generated by Django 4.2.6 on 2023-11-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_customuser_is_palestrante_palestrante_is_visitant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palestrante",
            name="training",
            field=models.CharField(max_length=20, verbose_name="formação"),
        ),
    ]
