# Generated by Django 4.2.6 on 2023-11-04 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_customuser_training"),
    ]

    operations = [
        migrations.CreateModel(
            name="PalestranteParaEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="evento",
            old_name="data_evento",
            new_name="data_fim",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="palestrantes",
        ),
        migrations.AddField(
            model_name="evento",
            name="data_inicio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dia e horário do evento"
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="is_fixed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evento",
            name="organizadores",
            field=models.ManyToManyField(
                related_name="organizadores_evento", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="eventos", verbose_name="foto"
            ),
        ),
    ]
