# Generated by Django 4.2.6 on 2023-11-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_palestranteparaevento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="data_fim",
            field=models.DateField(verbose_name="Dia e horário do evento"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="data_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Dia e horário do evento"
            ),
        ),
    ]
