# Generated by Django 4.2.6 on 2023-11-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_evento_data_fim_alter_evento_data_inicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="data_fim",
            field=models.DateField(verbose_name="da final do evento"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="data_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data inicio do evento"
            ),
        ),
    ]
