# Generated by Django 4.2.6 on 2023-11-04 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_alter_evento_data_fim_alter_evento_data_inicio"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PalestranteParaEvento",
            new_name="AtividadeParaEvento",
        ),
        migrations.CreateModel(
            name="DatasParaEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Dia para evento")),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.evento",
                    ),
                ),
            ],
        ),
    ]
