# Generated by Django 4.2.6 on 2023-11-04 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_rename_palestranteparaevento_atividadeparaevento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.evento",
                    ),
                ),
                (
                    "palestrantes",
                    models.ManyToManyField(
                        related_name="atividade_palestrante", to="accounts.palestrante"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AtividadeParaEvento",
        ),
        migrations.AddField(
            model_name="datasparaevento",
            name="data_adicionado",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="datasparaevento",
            name="atividades",
            field=models.ManyToManyField(
                related_name="atividades_para_data", to="accounts.atividade"
            ),
        ),
    ]
