# Generated by Django 4.2.6 on 2023-11-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_atividade_membros"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="is_event",
            field=models.BooleanField(default=False),
        ),
    ]
