# Generated by Django 4.2.6 on 2023-11-07 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_atividade_is_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="data_adicionado",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="atividade",
            name="horario_fim",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atividade",
            name="horario_inicio",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
