# Generated by Django 4.2.6 on 2023-11-08 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_atividade_data_adicionado_atividade_horario_fim_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atividade",
            name="evento",
        ),
        migrations.AddField(
            model_name="atividade",
            name="data_rel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.datasparaevento",
                verbose_name="Data da atividade",
            ),
        ),
        migrations.AddField(
            model_name="atividade",
            name="local",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
