# Generated by Django 4.2.6 on 2023-11-12 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_alter_atividade_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtividadeAlunos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=110)),
                ("descricao", models.TextField()),
                ("local", models.CharField(max_length=25)),
                ("data_expira", models.DateField()),
                ("data_apresentacao", models.DateTimeField()),
                ("link", models.URLField(max_length=210)),
                (
                    "data_adicionado",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "add_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membros",
                    models.ManyToManyField(
                        related_name="membros_atividades", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
