# Generated by Django 4.2.6 on 2023-11-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_atividadealunos"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividadealunos",
            name="type_publication",
            field=models.CharField(
                blank=True,
                choices=[("search", "pesquisa"), ("presentation", "apresentação")],
                max_length=13,
                null=True,
            ),
        ),
    ]
