# Generated by Django 4.2.6 on 2023-11-12 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_atividadealunos_type_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividadealunos",
            name="project_options",
            field=models.CharField(
                blank=True,
                choices=[("init", "inicio"), ("end", "fim")],
                max_length=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="atividadealunos",
            name="data_apresentacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="atividadealunos",
            name="link",
            field=models.URLField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name="atividadealunos",
            name="local",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="atividadealunos",
            name="membros",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="membros_atividades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="atividadealunos",
            name="type_publication",
            field=models.CharField(
                blank=True,
                choices=[
                    ("search", "pesquisa"),
                    ("presentation", "apresentação"),
                    ("project", "projeto"),
                ],
                max_length=13,
                null=True,
            ),
        ),
    ]
