# Generated by Django 4.2.6 on 2023-11-12 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0024_atividadealunos_project_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividadealunos",
            name="membros",
            field=models.ManyToManyField(
                blank=True,
                related_name="membros_atividades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
