# Generated by Django 4.2.6 on 2023-11-13 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_atividadealunos_curtidas_atividadealunos_interests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividadealunos",
            name="curtidas",
            field=models.ManyToManyField(
                blank=True,
                related_name="cutidas_atividades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="atividadealunos",
            name="interests",
            field=models.ManyToManyField(
                blank=True,
                related_name="interesses_atividades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
