# Generated by Django 4.2.6 on 2023-11-13 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0028_comentarios"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comentarios",
            new_name="Comentario",
        ),
    ]
