# Generated by Django 4.2.6 on 2023-11-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0029_rename_comentarios_comentario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividadealunos",
            name="data_expira",
            field=models.DateField(blank=True, null=True),
        ),
    ]
