# Generated by Django 4.2.6 on 2023-11-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0030_alter_atividadealunos_data_expira"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividadealunos",
            name="descricao",
            field=models.TextField(max_length=90),
        ),
    ]
