# Generated by Django 4.2.6 on 2023-11-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0032_alter_atividadealunos_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividadealunos",
            name="nome_projeto",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
